# source 'http://ruby.taobao.org'
source 'http://ruby.taobao.org/'

gem 'rails', '6.1.7.3'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

# gem 'sqlite3'

gem 'capistrano'

gem 'json', '>= 2.3.0'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails', '~> 5.0.8'
  gem 'coffee-rails', '~> 4.2.2'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 2.7.2'
end

gem 'jquery-rails', '>= 4.4.0'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug'

gem 'will_paginate', '>= 3.0.5'

group :production do
  gem 'mysql'
end

group :development do
  gem 'sqlite3'
end

group :test do
  gem 'sqlite3'
end
